spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/car_pool
    username: username
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  file:
    upload:
      photos-output-path: ./uploads
