spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    timeout: 30m
  mail:
    host: smtp.gmail.com
    port: 587
    username: no.reply.car.pool.hi@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
    session:
      cookie:
        same-site: None
        secure: true
  port: 8088
