spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    upload:
      photos-output-path: ./uploads
  session:
    timeout: 30m
  mail:
    host: smtp.gmail.com
    port: 587
    username: no.reply.car.pool.hi@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
    session:
      cookie:
        same-site: None
        secure: true
  port: 8080  # Azure App Service assigns port via PORT env variable

# Heroku-style:
# port: ${PORT:8080}
